CREATE TABLE `plans` (
  `plan_id` int(11) NOT NULL AUTO_INCREMENT,
  `plan_type_id` int(15) NULL,
  `carrier_id` int(15) NULL,
  `zip_code` varchar(5) DEFAULT NULL,
  `county_name` text,
  `state_name` text,
  `name` text,
  `addrs1` text,
  `city` text,
  `abbrev` text,
  `zip` text,
  `web_addr` text,
  `textcond` text,
  `sp_textcond` text,
  `description` text,
  `over65` smallint(5) DEFAULT NULL,
  `under65` smallint(5) DEFAULT NULL,
  `na_available` smallint(5) DEFAULT NULL,
  `community` smallint(5) DEFAULT NULL,
  `issue` smallint(5) DEFAULT NULL,
  `attained` smallint(5) DEFAULT NULL,
  `na_rating` smallint(5) DEFAULT NULL,
  `last_mod` text,
  PRIMARY KEY PK_PLANS(`plan_id`),
  FOREIGN KEY FK1_PLANS(`plan_type_id`) REFERENCES `plan_types`(`plan_type_id`),
  FOREIGN KEY FK2_PLANS(`carrier_id`) REFERENCES `carriers`(`carrier_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
