CREATE TABLE `plan_types` (
  `plan_type_id` int(11) NOT NULL AUTO_INCREMENT,
  `short_desc` varchar(255) NOT NULL,
  `long_desc` text,
  PRIMARY KEY PK_PLAN_TYPES(`plan_type_id`),
  KEY `IX1_PLAN_TYPES`(`short_desc`)
) ENGINE=InnoDB;

CREATE TABLE `plans` (
  `plan_id` int(11) NOT NULL AUTO_INCREMENT,
  `plan_type_id` int(15) NULL,
  `org_id` int(11) NULL,
  `textcond` text,
  `sp_textcond` text,
  `description` text,
  `over65` smallint(5) DEFAULT NULL,
  `under65` smallint(5) DEFAULT NULL,
  `na_available` smallint(5) DEFAULT NULL,
  `community` smallint(5) DEFAULT NULL,
  `issue` smallint(5) DEFAULT NULL,
  `attained` smallint(5) DEFAULT NULL,
  `na_rating` smallint(5) DEFAULT NULL,
  `montly_premium` decimal(12, 2) default null,
  `health_deductable` decimal(12, 2) default null,
  `drug_deductable` decimal(12, 2) default null,
  `plan_important_note` mediumtext,
  `dt_created` timestamp default current_timestamp,
  `dt_modified` timestamp default current_timestamp,
  PRIMARY KEY PK_PLANS(`plan_id`),
  FOREIGN KEY FK1_PLANS(`plan_type_id`) REFERENCES `plan_types`(`plan_type_id`),
  FOREIGN KEY FK2_PLANS(`org_id`) REFERENCES `orgs`(`org_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

create table `contracts` (
  `contract_id` int(11) NOT NULL,
  `contract_code` varchar(15),
  `plan_id` int(11) NOT NULL,
  `contract_important_note` mediumtext,
  PRIMARY KEY PK_CONTRACTS(`contract_id`),
  UNIQUE UQ1_CONTRACTS(`contract_code`, `plan_id`),
  FOREIGN KEY FK1_CONTRACTS(`plan_id`) REFERENCES `plans`(`plan_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `planinfo` (
  `contract_id` mediumtext NOT NULL,
  `plan_id` mediumtext NOT NULL,
  `segment_id` mediumtext,
  `contract_year` mediumtext NOT NULL,
  `org_name` mediumtext,
  `plan_name` mediumtext,
  `sp_plan_name` mediumtext,
  `geo_name` mediumtext,
  `tax_stus_cd` varchar(2) DEFAULT NULL,
  `tax_status_desc` mediumtext,
  `sp_tax_status_desc` mediumtext,
  `plan_type` int(11) NOT NULL DEFAULT '0',
  `plan_type_desc` mediumtext,
  `web_address` mediumtext,
  `partd_wb_adr` mediumtext,
  `frmlry_wbst_adr` mediumtext,
  `phrmcy_wbst_adr` mediumtext,
  `fed_approval_status` mediumtext,
  `sp_fed_approval_status` mediumtext,
  `pos_available_flag` mediumtext,
  `mail_ordr_avlblty` mediumtext,
  `cvrg_gap_ofrd` mediumtext,
  `cvrg_gap_ind` int(11) DEFAULT NULL,
  `cvrg_gap_desc` mediumtext,
  
  `sp_contract_important_note` mediumtext,
  `plan_important_note` mediumtext,
  `sp_plan_important_note` mediumtext,
  `segment_important_note` mediumtext,
  `sp_segment_important_note` mediumtext,
  `legal_entity_name` mediumtext,
  `trade_name` mediumtext,
  `network_english` mediumtext,
  `network_spanish` mediumtext,
  `contact_person` mediumtext,
  `street_address` mediumtext,
  `city` mediumtext,
  `state_code` mediumtext,
  `zip_code` mediumtext,
  `email_prospective` mediumtext,
  `local_phone_prospective` mediumtext,
  `tollfree_phone_prospective` mediumtext,
  `local_tty_prospective` mediumtext,
  `tollfree_tty_prospective` mediumtext,
  `email_current` mediumtext,
  `local_phone_current` mediumtext,
  `tollfree_phone_current` mediumtext,
  `local_tty_current` mediumtext,
  `tollfree_tty_current` mediumtext,
  `contact_person_pd` mediumtext,
  `street_address_pd` mediumtext,
  `city_pd` mediumtext,
  `state_code_pd` mediumtext,
  `zip_code_pd` mediumtext,
  `email_prospective_pd` mediumtext,
  `local_phone_prospective_pd` mediumtext,
  `tollfree_phone_prospective_pd` mediumtext,
  `local_tty_prospective_pd` mediumtext,
  `tollfree_tty_prospective_pd` mediumtext,
  `email_current_pd` mediumtext,
  `local_phone_current_pd` mediumtext,
  `tollfree_phone_current_pd` mediumtext,
  `local_tty_current_pd` mediumtext,
  `tollfree_tty_current_pd` mediumtext,
  `ma_pd_indicator` mediumtext,
  `ppo_pd_indicator` mediumtext,
  `snp_id` varchar(2) DEFAULT NULL,
  `snp_desc` mediumtext,
  `sp_snp_desc` mediumtext,
  `lis_100` mediumtext,
  `lis_75` mediumtext,
  `lis_50` mediumtext,
  `lis_25` mediumtext,
  `regional_indicator` mediumtext,
  `CountyFIPSCode` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;